version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:latest
    environment:
      REDIS_ARGS: --requirepass root
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
